"""playlists is fav

Revision ID: 875b05697722
Revises: c8e2da18784a
Create Date: 2025-10-03 18:43:51.261468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875b05697722'
down_revision: Union[str, Sequence[str], None] = 'c8e2da18784a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'is_favourite', new_column_name='is_favorite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'is_favorite', new_column_name='is_favourite')
    # ### end Alembic commands ###
