"""empty message

Revision ID: da7be1a2c1a5
Revises: c95deb9000a2
Create Date: 2025-09-29 13:46:30.953711

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da7be1a2c1a5'
down_revision: Union[str, Sequence[str], None] = 'c95deb9000a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('is_favourite', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'is_favourite')
    # ### end Alembic commands ###
