"""updated at triggers

Revision ID: ea21f0190e95
Revises: 875b05697722
Create Date: 2025-10-03 18:51:38.843850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea21f0190e95'
down_revision: Union[str, Sequence[str], None] = '875b05697722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS trigger AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trg_set_updated_at
    BEFORE UPDATE ON playlists
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
    """)

    op.execute("""
    CREATE TRIGGER trg_set_updated_at
    BEFORE UPDATE ON songs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_set_updated_at ON playlists;")
    op.execute("DROP TRIGGER IF EXISTS trg_set_updated_at ON songs;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at;")
    # ### end Alembic commands ###
