name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          
          cd ~/beat-buddy-backend
          git fetch origin
          git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
          git reset --hard origin/${{ github.ref_name }}

          docker compose down --remove-orphans
          docker compose pull
          docker compose build --no-cache
          docker compose up -d
          
          docker compose ps
          docker compose logs --tail=50
