name: Run tests with coverage

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: localhost
      DB_PORT: 5432
      TEST_DB_NAME: test_db # TODO: later change to DB_NAME
      ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: make ci-coverage

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          github-token: ${{ secrets.PAT_TOKEN }}
